import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>my-portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* HEADER goes here */}

      {/* BRANDING PAGE */}

      {/* ABOUT SECTION GOES HERE */}

      {/* SERVICES SECTION GOES HERE */}

      {/* CONTACT ME PAGE GOES HERE */}
    </div>
  );
}
